version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./backend/backend.dockerfile
    volumes:
      - ./backend/:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    ports:
      - 8001:5432

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - api
      - front

  front:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    env_file:
      - ./.env.front
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api

  celery:
    build:
      context: ./
      dockerfile: ./backend/celery.dockerfile
    command: celery --app=core worker --loglevel=info
    volumes:
      - ./backend:/home/app/web
    env_file:
      - ./.env
    depends_on:
      - api
      - redis

  celery-flower:
    build:
      context: ./
      dockerfile: ./backend/celery.dockerfile
    command: celery flower -A core --port=5555
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - api
      - redis

  celery-beat:
    build:
      context: ./
      dockerfile: ./backend/celery.dockerfile
    command: celery --app=core beat --loglevel=info
    volumes:
      - ./backend:/home/app/web
    env_file:
      - ./.env
    depends_on:
      - api
      - redis

  redis:
    image: redis:7-alpine

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
  minio-client:
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet local/tech-recruiter/;
      /usr/bin/mc anonymous set download local/tech-recruiter/;
      "
    depends_on:
      - minio


volumes:
  postgres_data:
  static_volume:
  media_volume:
  minio_data:

