# Generated by Django 5.0.3 on 2024-04-13 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelTable(
            name="post",
            table="posts",
        ),
    ]
