# Generated by Django 5.0.3 on 2024-06-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                null=True, upload_to="blog_posts", verbose_name="Обложка"
            ),
        ),
    ]
