# Generated by Django 5.0.3 on 2024-06-02 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
    ]
