# Generated by Django 5.0.3 on 2024-06-03 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_tag_options"),
        ("blog", "0006_alter_tag_options_post_image"),
    ]

    operations = []
