# Generated by Django 4.2.1 on 2024-03-31 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="telegram_id",
            new_name="telegram_nickname",
        ),
    ]
