# Generated by Django 4.2.1 on 2024-03-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_telegram_id_profile_telegram_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/profiles"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telegram_nickname",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
