# Generated by Django 5.0.3 on 2024-04-13 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Профили"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "Пользователи"},
        ),
    ]
