# Generated by Django 5.0.3 on 2024-04-26 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_profile_options_alter_user_options_and_more"),
        ("users", "0010_profile_birth_date"),
    ]

    operations = []
