# Generated by Django 5.0.3 on 2024-05-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_profile_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="users/profiles",
                verbose_name="Фото профиля",
            ),
        ),
    ]
