# Generated by Django 5.0.3 on 2024-05-18 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0006_module_unique_course_module_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидается"),
                            ("paid", "Оплачено"),
                            ("canceled", "Отменено"),
                        ],
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Id платежа"
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(blank=True, null=True, verbose_name="URL платежа"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
