# Generated by Django 5.0.3 on 2024-04-26 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("views", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialview",
            options={"verbose_name_plural": "Просмотры материалов по урокам"},
        ),
        migrations.AlterModelOptions(
            name="videoview",
            options={"verbose_name_plural": "Просмотры видеоуроков"},
        ),
    ]
