# Generated by Django 5.0.3 on 2024-05-10 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_course_category"),
        ("views", "0003_alter_materialview_material_alter_materialview_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="materialview",
            constraint=models.UniqueConstraint(
                fields=("user", "material"), name="single_material_view"
            ),
        ),
        migrations.AddConstraint(
            model_name="videoview",
            constraint=models.UniqueConstraint(
                fields=("user", "video"), name="single_video_view"
            ),
        ),
    ]
