# Generated by Django 5.0.3 on 2024-05-30 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_tests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessontest",
            name="module",
        ),
    ]
