# Generated by Django 5.0.3 on 2024-05-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_tests", "0002_remove_lessontest_module"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontest",
            name="lesson",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="lessons.lesson",
                verbose_name="Урок",
            ),
            preserve_default=False,
        ),
    ]
