# Generated by Django 5.0.3 on 2024-06-02 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lesson_tests",
            "0004_remove_answer_user_alter_answer_option_solution_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="solution",
            constraint=models.UniqueConstraint(
                fields=("user", "test"), name="unique_user_test"
            ),
        ),
    ]
