# Generated by Django 5.0.3 on 2024-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrolls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enroll",
            options={
                "verbose_name": "Запись на курс",
                "verbose_name_plural": "Записи на курсы",
            },
        ),
        migrations.AlterField(
            model_name="enroll",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Была создана"),
        ),
    ]
