# Generated by Django 5.0.3 on 2024-05-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrolls", "0002_alter_enroll_options_alter_enroll_created_at"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enroll",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
    ]
