# Generated by Django 5.0.3 on 2024-04-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_category_options_alter_course_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Категории курсов"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lessonmaterial",
            options={"verbose_name_plural": "Материалы к урокам"},
        ),
        migrations.AlterModelOptions(
            name="lessonvideo",
            options={"verbose_name_plural": "Видеоуроки"},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name_plural": "Модули"},
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
            ),
        ),
    ]
