# Generated by Django 5.0.3 on 2024-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_module_unique_course_module_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonvideo",
            name="module",
        ),
        migrations.DeleteModel(
            name="LessonMaterial",
        ),
        migrations.DeleteModel(
            name="LessonVideo",
        ),
    ]
