# Generated by Django 5.0.3 on 2024-05-31 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_category_slug_course_slug_module_slug"),
        ("courses", "0007_remove_lessonvideo_module_delete_lessonmaterial_and_more"),
    ]

    operations = []
