# Generated by Django 5.0.3 on 2024-07-06 09:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_merge_20240531_1002"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Содержание"),
                ),
            ],
            options={
                "verbose_name_plural": "Афферты",
                "db_table": "afferts",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="affert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.affert",
                verbose_name="Афферт",
            ),
        ),
    ]
