# Generated by Django 5.0.3 on 2024-07-07 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_rename_price_course_pricex_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name_plural": "Цены"},
        ),
        migrations.AlterModelTable(
            name="price",
            table="course_prices",
        ),
    ]
