# Generated by Django 5.0.3 on 2024-08-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_alter_price_options_alter_price_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affert",
            options={"verbose_name": "оферта", "verbose_name_plural": "оферты"},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name": "Цена", "verbose_name_plural": "Цены"},
        ),
        migrations.AlterField(
            model_name="price",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
    ]
