# Generated by Django 5.0.3 on 2024-08-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_alter_affert_options_alter_price_options_and_more"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tutors.tutor",
            ),
        ),
    ]
