# Generated by Django 5.0.3 on 2024-08-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_module_tutor"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["course", "ordinal_number"],
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="block1_content1",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к первому блоку первому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_content2",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к первому блоку второму отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_content3",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к первому блоку третьему отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_content4",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к первому блоку четвертому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_subtitle1",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Подзаголовок к первому блоку первому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_subtitle2",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Подзаголовок к первому блоку второму отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_subtitle3",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Подзаголовок к первому блоку третьему отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_subtitle4",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Подзаголовок к первому блоку четвертому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block1_title",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Заголовок к первому блоку",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_content1",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к первому блоку первому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_content2",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к второму блоку второму отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_content3",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к второму блоку третьему отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_content4",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Контент к второму блоку четвертому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_subtitle1",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Заголовок ко второму блоку первому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_subtitle2",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Заголовок ко второму блоку второму отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_subtitle3",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Заголовок ко второму блоку третьему отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_subtitle4",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Заголовок ко второму блоку четвертому отделу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="block2_title",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Заголовок ко второму блоку",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="module",
            name="tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="tutors.tutor",
                verbose_name="Автор",
            ),
        ),
    ]
