# Generated by Django 5.0.3 on 2024-08-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_module_tutor"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["course", "ordinal_number"],
                "verbose_name": "Модуль",
                "verbose_name_plural": "Модули",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="affert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.affert",
                verbose_name="Оферта",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="tutors.tutor",
                verbose_name="Автор",
            ),
        ),
    ]
