# Generated by Django 5.0.3 on 2024-08-15 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_alter_module_options_alter_course_affert_and_more"),
        ("courses", "0014_alter_module_options_course_block1_content1_and_more"),
    ]

    operations = []
