# Generated by Django 5.0.3 on 2024-07-07 09:43

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lessons", "0004_lesson_course_alter_lesson_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Содержание"),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                ("file", models.FileField(upload_to="homeworks", verbose_name="Файл")),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework",
                        to="lessons.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Домашние задания",
                "db_table": "homeworks",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Содержание"),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                ("file", models.FileField(upload_to="homeworks", verbose_name="Файл")),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="homeworks.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hw_solutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ответы к домашним заданиям",
                "db_table": "solutions",
            },
        ),
    ]
