# Generated by Django 5.0.3 on 2024-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="Полное имя"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(upload_to="tutors", verbose_name="Изображение"),
                ),
            ],
            options={
                "verbose_name": "Наставник",
                "verbose_name_plural": "Наставники",
                "db_table": "tutors",
            },
        ),
    ]
