# Generated by Django 5.0.3 on 2024-07-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_lesson_course_alter_lesson_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="materials", verbose_name="Файл"
            ),
        ),
    ]
