# Generated by Django 5.0.3 on 2024-08-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_alter_module_options_alter_course_affert_and_more"),
        ("lessons", "0005_material_link_alter_material_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="title",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
                verbose_name="Модуль",
            ),
        ),
    ]
